search_parameters:
  metal_ion: "ZN"
  # resolution_cutoff: 2.0
  experimental_method: "X-RAY DIFFRACTION"
  polymer_type: null 

processing:
  batch_size: 75
  parallel_workers: 4
  rate_limit_delay: 0.1
  max_downloads: 1500
  cutoff: 2.6
  selection_radius: 3.5
  target: "ZN"
  metals_excluded: []
  must_have: "S>=2,N>=2"  # change for different ligand reqs
  include_waters: false

output:
  base_output_dir: "./data/exp-compare/"
  save_matching_structures: true

validation:
  coordination_distance_min: 2.0
  coordination_distance_max: 3.2
  ligand_requirements:  # change for different ligand reqs
    - resname: CYS
      atom_names: [SG]
      count: 2
    - resname: HIS
      atom_names: [ND1, NE2]
      count: 2

input_mode: "list_file"
input_data: ["exp-ids.txt"]
log_level: "INFO"
